### PR TITLE
Fix adding recipients. Fixes #1500.

### LINKED ISSUE #1500: RNP CLI: Show some error message if encryption failed due to expired recipient's key.
## Description

RNP CLI doesn't show any error message if encryption failed because of expired recipient's key.

## Steps to Reproduce

`rnp -r "expired_key" somefile.dat`

## Expected Behavior

Some message is shown, like `Encryption failed: recipient's key "expired_key" is expired.`

## Actual Behavior

No message at all (however, return code is correct and non-zero).

### PR DESCRIPTION
**Pull request by antonsviridenko**
`rnp_op_encrypt_add_recipient()` did not check return value from `find_suitable_key()` so in some cases NULL pointer could have been added to recipients lists, which caused failures on later stages.

Let's discuss if we need to print rejection reason for each key, primary and subkeys.

### CODE REVIEW

**Comment by antonsviridenko** [comment]
All centos checks fail with `Error: Unable to find a match: cmake3`

**Comment by ronaldtse** [comment]
Ping @ribose-jeffreylau re: CentOS 8 failures on `cmake3`

**Comment by ni4** [comment]
@antonsviridenko
I think we should not change behaviour in this way, as implementations which worked before by checking `rnp_op_encrypt_execute()` return code will fail now to get to that step. Also, there could be other reasons in the future why recipient's key is unusable for encryption, and we should not check all of these in `rnp_op_encrypt_add_recipient()` (functionality duplication). Another thing is issue #1446 - there are some cases when we should ignore times.

Instead I suggest the following changes:

- update documentation of `rnp_op_encrypt_add_recipient()`, telling that it doesn't do any checks on key expiration and that should be done manually.
- print error message in CLI, when encryption fails due to any reasons.
- once #1457 is implemented - add check in the CLI for default key/subkey expiration, telling that to the user and failing operation.

P.S. Btw, it looks like Github doesn't link issue to the PR if issue's number is on the title.

**Comment by antonsviridenko** [comment]
@ni4 what about this part?

> rnp_op_encrypt_add_recipient() did not check return value from find_suitable_key() so in some cases NULL pointer could have been added to recipients lists, which caused failures on later stages.

https://github.com/rnpgp/rnp/blob/e43d5b1cfeba441e82e3c0153b9432cbb8131003/src/lib/rnp.cpp#L2323

Saving NULL pointer to recipients is clearly a bug to me, 
if we don't want to change behavior of `rnp_op_encrypt_add_recipient()`, then I think if `find_suitable_key()` returns NULL, `get_key_prefer_public(handle)` value should be saved into `recipients` std::list.

**Comment by ni4** [comment]
> @ni4 what about this part?
> 
> > rnp_op_encrypt_add_recipient() did not check return value from find_suitable_key() so in some cases NULL pointer could have been added to recipients lists, which caused failures on later stages.
> 
> https://github.com/rnpgp/rnp/blob/e43d5b1cfeba441e82e3c0153b9432cbb8131003/src/lib/rnp.cpp#L2323
> 
> Saving NULL pointer to recipients is clearly a bug to me,
> if we don't want to change behavior of `rnp_op_encrypt_add_recipient()`, then I think if `find_suitable_key()` returns NULL, `get_key_prefer_public(handle)` value should be saved into `recipients` std::list.

Sorry, mislooked this. Yeah, let's store public key and let it be handled afterwards. Also this case (sign-only primary key + sign-only subkeys/invalid subkeys) should be covered with tests if it didn't yet.

File: src/lib/pgp-key.cpp [hunk 1]
```diff
@@ -566,7 +566,7 @@ find_suitable_key(pgp_op_t            op,
     if (!key) {
         return NULL;
     }
-    if (key->flags() & desired_usage) {
+    if (key->valid() && key->flags() & desired_usage) {
```
Comment (ni4) [inline src/lib/pgp-key.cpp:569]: Please add brackets here for better readability.

File: src/lib/rnp.cpp [hunk 2]
```diff
@@ -2317,6 +2317,9 @@ try {
                                        get_key_prefer_public(handle),
                                        &handle->ffi->key_provider,
                                        PGP_KF_ENCRYPT);
+    if (!key) {
```
Comment (ni4) [inline src/lib/rnp.cpp:2320]: Please add or update existing test which checks this case (i.e., for instance, attempt to add sign-only primary key with invalid or expired subkey for encryption), and check for failure of `rnp_op_encrypt_execute()` afterwards. That way we'll be sure that behaviour doesn't change in future/there are no memory leaks or other failures if incorrect key used for encryption attempt.

**Review by ni4 — CHANGES_REQUESTED** [review]
Overall LGTM, just minor change and please add/update test. Thanks!

File: src/lib/rnp.cpp (hunk 2 above)
Comment (antonsviridenko) [reply src/lib/rnp.cpp:2320]: @ni4 this case is already covered in https://github.com/rnpgp/rnp/blob/master/src/tests/ffi-enc.cpp#L852 - sign-only primary key and expired subkey

Comment (ni4) [reply src/lib/rnp.cpp:2320]: @antonsviridenko Thanks, then no new test is needed.
P.S. Don't be shocked by all red CI - it's because of key expiration used in tests, marking key as expired. I'll issue PR fixing that.

**Review by ronaldtse — APPROVED** [review]
Most tests should pass now on rebase?

**Comment by antonsviridenko** [comment]
ruby-rnp tests fail...

**Comment by ronaldtse** [comment]
@antonsviridenko the ruby-rnp failure, e.g.
https://github.com/rnpgp/rnp/pull/1520/checks?check_run_id=2922229337

Is identical to #1539 .

**Comment by ni4** [comment]
@antonsviridenko Please rebase on the latest master. Issue is fixed within PR #1531

**Review by ni4 — APPROVED** [review]
LGTM, thanks! Feel free to rebase and merge once CI passes.
