### PR TITLE
Fix possible rare failure in test_key_unlock_pgp() test.

### LINKED ISSUE #994: Possible rare error in test test_key_unlock_pgp.
## Description

Under ubuntu with (normal, beta) configuration got this single errored test.
Under other oses and previously it worked well.

## Log

```
[==========] Running 1 test from 1 test suite.
2019-12-05T14:58:30.1893388Z [----------] Global test environment set-up.
2019-12-05T14:58:30.1893644Z [----------] 1 test from rnp_tests
2019-12-05T14:58:30.1893731Z [ RUN      ] rnp_tests.test_key_unlock_pgp
2019-12-05T14:58:30.1894073Z [signature_check_binding() /home/runner/work/rnp/rnp/src/librepgp/stream-sig.cpp:1210] subkey expired 64360857 seconds ago
2019-12-05T14:58:30.1894388Z [signature_check_binding() /home/runner/work/rnp/rnp/src/librepgp/stream-sig.cpp:1210] subkey expired 64360857 seconds ago
2019-12-05T14:58:30.1894722Z [signature_check_binding() /home/runner/work/rnp/rnp/src/librepgp/stream-sig.cpp:1210] subkey expired 64360858 seconds ago
2019-12-05T14:58:30.1895042Z [signature_check_binding() /home/runner/work/rnp/rnp/src/librepgp/stream-sig.cpp:1210] subkey expired 64360858 seconds ago
2019-12-05T14:58:30.1895369Z [signed_fill_signature() /home/runner/work/rnp/rnp/src/librepgp/stream-write.cpp:1088] wrong secret key password
2019-12-05T14:58:30.1895919Z [signed_dst_finish() /home/runner/work/rnp/rnp/src/librepgp/stream-write.cpp:1146] failed to calculate signature
2019-12-05T14:58:30.1896223Z [process_stream_sequence() /home/runner/work/rnp/rnp/src/librepgp/stream-write.cpp:1737] failed to finish stream
2019-12-05T14:58:30.1935158Z Good signature made Thu Dec  5 14:58:29 2019
2019-12-05T14:58:30.1935513Z using RSA (Encrypt or Sign) key 7bc6709b15c23a4a
2019-12-05T14:58:30.1935752Z 
2019-12-05T14:58:30.1936478Z pub   1024/RSA (Encrypt or Sign) 7bc6709b15c23a4a 2017-07-20 [SC]
2019-12-05T14:58:30.1936591Z       e95a3cbf583aa80a2ccc53aa7bc6709b15c23a4a
2019-12-05T14:58:30.1936892Z uid           key0-uid0
2019-12-05T14:58:30.1937109Z uid           key0-uid1
2019-12-05T14:58:30.1937318Z uid           key0-uid2
2019-12-05T14:58:30.1937560Z Signature(s) verified successfully
2019-12-05T14:58:30.1937648Z Good signature made Thu Dec  5 14:58:29 2019
2019-12-05T14:58:30.1937748Z using RSA (Encrypt or Sign) key 7bc6709b15c23a4a
2019-12-05T14:58:30.1937793Z 
2019-12-05T14:58:30.1938732Z pub   1024/RSA (Encrypt or Sign) 7bc6709b15c23a4a 2017-07-20 [SC]
2019-12-05T14:58:30.1938858Z       e95a3cbf583aa80a2ccc53aa7bc6709b15c23a4a
2019-12-05T14:58:30.1939135Z uid           key0-uid0
2019-12-05T14:58:30.1939408Z uid           key0-uid1
2019-12-05T14:58:30.1939913Z uid           key0-uid2
2019-12-05T14:58:30.1940017Z Signature(s) verified successfully
2019-12-05T14:58:30.1940314Z /home/runner/work/rnp/rnp/src/tests/key-unlock.cpp:152: Failure
2019-12-05T14:58:30.1940433Z Value of: (cli_rnp_process_file(&cfg, &rnp))
2019-12-05T14:58:30.1940541Z   Actual: true
2019-12-05T14:58:30.1940643Z Expected: false
2019-12-05T14:58:30.1940998Z [signed_fill_signature() /home/runner/work/rnp/rnp/src/librepgp/stream-write.cpp:1088] wrong secret key password
2019-12-05T14:58:30.1941395Z [signed_dst_finish() /home/runner/work/rnp/rnp/src/librepgp/stream-write.cpp:1146] failed to calculate signature
2019-12-05T14:58:30.1941927Z [process_stream_sequence() /home/runner/work/rnp/rnp/src/librepgp/stream-write.cpp:1737] failed to finish stream
2019-12-05T14:58:30.1942252Z [init_encrypted_src() /home/runner/work/rnp/rnp/src/librepgp/stream-parse.cpp:1970] failed to obtain decrypting key or password
2019-12-05T14:58:30.1942576Z [init_encrypted_src() /home/runner/work/rnp/rnp/src/librepgp/stream-parse.cpp:1970] failed to obtain decrypting key or password
2019-12-05T14:58:30.1942669Z [  FAILED  ] rnp_tests.test_key_unlock_pgp (1254 ms)
2019-12-05T14:58:30.1943093Z [----------] 1 test from rnp_tests (1255 ms total)
2019-12-05T14:58:30.1943159Z 
2019-12-05T14:58:30.1943378Z [----------] Global test environment tear-down
2019-12-05T14:58:30.1943472Z [==========] 1 test from 1 test suite ran. (1255 ms total)
2019-12-05T14:58:30.1943564Z [  PASSED  ] 0 tests.
2019-12-05T14:58:30.1943810Z [  FAILED  ] 1 test, listed below:
2019-12-05T14:58:30.1943880Z [  FAILED  ] rnp_tests.test_key_unlock_pgp
```

### PR DESCRIPTION
**Pull request by ni4**
It's quite logical that we should not attempt to modify the signature by writing constant value inside of it - it may match already existing one in 1 in 256 cases.

Fixes #994

### CODE REVIEW

File: src/tests/key-unlock.cpp [hunk 1]
```diff
@@ -147,7 +147,11 @@ TEST_F(rnp_tests, test_key_unlock_pgp)
                       std::ios_base::binary | std::ios_base::out | std::ios_base::in);
     off_t        versize = file_size("dummyfile.dat.pgp");
     verf.seekg(versize - 3, std::ios::beg);
-    verf.write("\x0C", 1);
+    char bt = 0;
+    verf.read(&bt, 1);
+    bt = bt ^ 0xff;
+    verf.seekg(versize - 3, std::ios::beg);
```
Comment (dewyatt) [inline src/tests/key-unlock.cpp]: Can you use peek instead of seeking twice?

Comment (dewyatt) [reply src/tests/key-unlock.cpp]: Good catch by the way.

Comment (ni4) [reply src/tests/key-unlock.cpp]: @dewyatt Sure. Will force-push in a moment.

Comment (ni4) [reply src/tests/key-unlock.cpp]: ..and thanks! )

Comment (ni4) [reply src/tests/key-unlock.cpp]: @dewyatt Hm, fstream appears to work in a bit strange way, as from https://stackoverflow.com/questions/15670359/fstream-seekg-seekp-and-write

> The implications of point 2 are that between reads and writes on an fstream you must either flush the buffer or seek the file position when changing from output to input, and you must either be at the end of the file or seek the file position when changing from input to output.`

Anyway, changed code a bit to not do call to `file_size()`

Comment (dewyatt) [reply src/tests/key-unlock.cpp]: @ni4 The wording is confusing there, but I believe the second seek call is now redundant because we're not reading or writing at that point, we're peeking.

However, it's just one line, I'm not too worried about it.
