### PR TITLE
Generating keys with multiple userids is unsupported.

### LINKED ISSUE #929: Generating a key with multiple userids silently ignores all but last userid
## Description

Generating a key with multiple userids silently ignores all but last userid.

## Steps to Reproduce

```
% rnpkeys --homedir /tmp/rnphome --generate-key --userid="foo@example.org" --userid="bar@example.org"
[init_file_src() /home/teythoon/repos/pep/pgpzoo/src/rnp/src/librepgp/stream-common.cpp:378] can't stat '/tmp/rnphome/pubring.gpg'
wrong pubring path
Generating a new key...

sec   2048/RSA (Encrypt or Sign) e5505fc4d404a055 2019-10-24 [SC]
      c997b53e214cfd14ae2453f3e5505fc4d404a055
uid           bar@example.org
ssb   2048/RSA (Encrypt or Sign) 55d1444a84b39413 2019-10-24 [E]
      130b33cffbe9ee5b784ffc8255d1444a84b39413
% rnpkeys --homedir /tmp/rnphome --export-key c997b53e214cfd14ae2453f3e5505fc4d404a055 | sq inspect
-: Transferable Public Key.

    Fingerprint: C997 B53E 214C FD14 AE24  53F3 E550 5FC4 D404 A055
Public-key algo: RSA (Encrypt or Sign)
Public-key size: 2048 bits
  Creation time: 2019-10-24T10:18
       Keyflags: certification, signing

         Subkey: 130B 33CF FBE9 EE5B 784F  FC82 55D1 444A 84B3 9413
Public-key algo: RSA (Encrypt or Sign)
Public-key size: 2048 bits
  Creation time: 2019-10-24T10:18
       Keyflags: transport encryption, data-at-rest encryption

         UserID: bar@example.org
```

## Expected Behavior

Preferably generate a key with two userids, failing that, signal an error that giving multiple `--userid` arguments is not supported.

## Actual Behavior

All but the last `--userid` parameters are silently ignored.

### PR DESCRIPTION
**Pull request by joke325**
Closes #929

### CODE REVIEW

File: src/rnp/rnpcfg.cpp [hunk 1]
```diff
@@ -247,6 +247,10 @@ rnp_cfg_setstr(rnp_cfg_t *cfg, const char *key, const char *val)
         return false;
     }
 
+    std::string mkey("\x01");
+    mkey.append(key);
+    rnp_cfg_addstr(cfg, mkey.c_str(), val? val : "");
+
```
Comment (ni4) [inline src/rnp/rnpcfg.cpp]: You don't need to modify function `rnp_cfg_setstr()` as required functionality is already implemented in `rnp_cfg_addstr()`. Please see how handled `OPT_USERID` and `CFG_SIGNERS` in `rnp.cpp`.

File: src/rnp/rnpcfg.cpp [hunk 2]
```diff
@@ -284,12 +288,26 @@ rnp_cfg_addstr(rnp_cfg_t *cfg, const char *key, const char *str)
...
 
 const char *
-rnp_cfg_getstr(const rnp_cfg_t *cfg, const char *key)
+rnp_cfg_getstr(const rnp_cfg_t *cfg, const char *key, const size_t item_idx)
 {
     rnp_cfg_item_t *it = rnp_cfg_find(cfg, key);
 
     if (it && (it->val.type == RNP_CFG_VAL_STRING)) {
-        return it->val.val._string;
+        if (item_idx == 0) {
```
Comment (ni4) [inline src/rnp/rnpcfg.cpp]: The same as previous comment - you don't need to modify this function since all required functionality is already implemented.

File: src/rnpkeys/rnpkeys.cpp [hunk 3]
```diff
@@ -254,6 +254,10 @@ rnp_cmd(rnp_cfg_t *cfg, cli_rnp_t *rnp, optdefs_t cmd, const char *f)
     case CMD_GENERATE_KEY: {
         if (f == NULL) {
             f = rnp_cfg_getstr(cfg, CFG_USERID);
+            if(rnp_cfg_getstr(cfg, CFG_USERID, 2) != NULL) {
```
Comment (ni4) [inline src/rnpkeys/rnpkeys.cpp]: You should use `rnp_cfg_getlist()` here, to quickly check it's length. Also here or later you may use more C++-ish wrapper `rnp_cfg_copylist_string()`.

File: src/rnpkeys/rnpkeys.cpp [hunk 4]
```diff
@@ -254,6 +254,10 @@ rnp_cmd(rnp_cfg_t *cfg, cli_rnp_t *rnp, optdefs_t cmd, const char *f)
...
+                fprintf(stderr, "only userid is supported for generated keys\n");
```
Comment (ni4) [inline src/rnpkeys/rnpkeys.cpp]: The idea of this PR was to update code to be able to generate keys with multiple user id's, not just report an error. While key generation function supports single key id at the moment, you still may use `rnp_key_add_uid()` on the generated key. Also it worth adding `rnp_op_generate_add_uid()` method, so user id would be added in a single pass.

File: src/tests/generatekey.cpp [hunk 5]
```diff
@@ -650,11 +650,14 @@ TEST_F(rnp_tests, rnpkeys_generatekey_testExpertMode)
...
 
-    assert_true(rnp_cfg_setbool(&ops, CFG_EXPERT, true));
-    assert_true(rnp_cfg_setint(&ops, CFG_S2K_ITER, 1));
+    assert_true(rnp_cfg_setbool(&tops, CFG_EXPERT, true));
+    assert_true(rnp_cfg_setint(&tops, CFG_S2K_ITER, 1));
 
     /* ecdsa/ecdh p256 keypair */
+    rnp_cfg_free(&ops);
+    rnp_cfg_copy(&ops, &tops);
     assert_true(rnp_cfg_setstr(&ops, CFG_USERID, "expert_ecdsa_p256"));
```
Comment (ni4) [inline src/tests/generatekey.cpp]: It would be better instead of modifying the whole test workflow just inset `rnp_cfg_unset()` calls. However, anyway, you should not modify inner code of `rnp_cfg_setstr()` and use `rnp_cfg_addstr()` or something similar.

**Comment by joke325** [comment]
@ni4 There (the issue @929) is stated the Expected Behavior:
"Preferably generate a key with two userids, failing that, signal an error that giving multiple --userid arguments is not supported."

File: src/rnp/fficli.cpp [hunk 6]
```diff
@@ -1466,20 +1466,27 @@ rnp_cfg_set_defkey(rnp_cfg_t *cfg)
     }
 
     /* If a userid has been given, we'll use it. */
-    if (!(userid = rnp_cfg_getstr(cfg, CFG_USERID))) {
+    userid = NULL;
+    list ids = NULL;
+    if (rnp_cfg_copylist_str(cfg, &ids, CFG_USERID)) {
+        userid = (char*)list_front(ids);
+    }
```
Comment (ni4) [inline src/rnp/fficli.cpp]: Instead of creating temporary list and copying data to it (and duplicate code below), it would be better to add helper function like `const std::string &rnp_cfg_getlist_string(const rnp_cfg_t *cfg, const std::string &key, size_t index)`. Inside you may use `rnp_cfg_getlist()` to check list's length and get value via `rnp_cfg_val_getstr()`.

File: src/rnpkeys/rnpkeys.cpp [hunk 7]
```diff
@@ -230,15 +230,27 @@ bool
...
 
     switch (cmd) {
     case CMD_LIST_KEYS:
         if (!f) {
-            f = rnp_cfg_getstr(cfg, CFG_USERID);
+            list ids = NULL;
+            if (rnp_cfg_copylist_str(cfg, &ids, CFG_USERID) && list_length(ids) > 0) {
+                f = (fs = (char*)list_front(ids)).c_str();
+            }
+            list_destroy(&ids);
```
Comment (ni4) [inline src/rnpkeys/rnpkeys.cpp]: As the previous - no need to duplicate list, while you can get the element via some helper function.

File: src/rnpkeys/rnpkeys.cpp [hunk 8]
```diff
@@ -230,15 +230,27 @@ bool
...
         return print_keys_info(cfg, rnp, stdout, f);
     case CMD_EXPORT_KEY: {
-        key = f ? f : rnp_cfg_getstr(cfg, CFG_USERID);
+        key = f;
+        if (!key) {
+            list ids = NULL;
+            if (rnp_cfg_copylist_str(cfg, &ids, CFG_USERID) && list_length(ids) > 0) {
+                key = (fs = (char*)list_front(ids)).c_str();
+            }
+            list_destroy(&ids);
```
Comment (ni4) [inline src/rnpkeys/rnpkeys.cpp]: As the previous.

File: src/rnpkeys/rnpkeys.cpp [hunk 9]
```diff
@@ -253,7 +265,17 @@ rnp_cmd(rnp_cfg_t *cfg, cli_rnp_t *rnp, optdefs_t cmd, const char *f)
...
-            f = rnp_cfg_getstr(cfg, CFG_USERID);
+            list ids = NULL;
+            if (rnp_cfg_copylist_str(cfg, &ids, CFG_USERID) && list_length(ids) > 0) {
+                if (list_length(ids) == 1) {
+                    f = (fs = (char*)list_front(ids)).c_str();
+                } else {
+                    fprintf(stderr, "only userid is supported for generated keys\n");
+                    list_destroy(&ids);
+                    return false;
+                }
```
Comment (ni4) [inline src/rnpkeys/rnpkeys.cpp]: As the previous - helper function + `list_length(rnp_cfg_get_list())` to check list's length.

File: src/rnp/fficli.cpp (hunk 6 above)
Comment (joke325) [reply src/rnp/fficli.cpp]: The rnp_cfg_val_getstr() doesn't support the RNP_CFG_VAL_LIST type.

Comment (ni4) [reply src/rnp/fficli.cpp]: @joke325 yeah, I mean something like `rnp_cfg_val_getstr((rnp_cfg_val_t*) list_front(rnp_cfg_getlist(cfg, name)))`

File: src/rnp/rnpcfg.cpp [hunk 10]
```diff
@@ -373,6 +373,19 @@ rnp_cfg_getlist(rnp_cfg_t *cfg, const char *key)
     return NULL;
 }
 
+std::string rnp_cfg_getlist_string(const rnp_cfg_t *cfg, const std::string &key, size_t index) {
+    list *lval = rnp_cfg_getlist(const_cast<rnp_cfg_t*>(cfg), key.c_str());
+    if (lval) {
```
Comment (ni4) [inline src/rnp/rnpcfg.cpp]: Here would be better to change to `if (!lval) {return ""}`, to have less nested code.

File: src/rnp/rnpcfg.cpp [hunk 11]
```diff
@@ -373,6 +373,19 @@ rnp_cfg_getlist(rnp_cfg_t *cfg, const char *key)
...
+        if (index < list_length(*lval)) {
+            rnp_cfg_val_t *val = (rnp_cfg_val_t *)list_at(*lval, index);
+            return rnp_cfg_val_getstr(val);
```
Comment (ni4) [inline src/rnp/rnpcfg.cpp]: `rnp_cfg_val_getstr()` may return NULL, which will raise an exception in std::string() constructor. Please check for NULL and return empty string in that case.

File: src/rnp/rnpcfg.cpp [hunk 12]
```diff
@@ -373,6 +373,19 @@ rnp_cfg_getlist(rnp_cfg_t *cfg, const char *key)
     return NULL;
 }
 
+std::string rnp_cfg_getlist_string(const rnp_cfg_t *cfg, const std::string &key, size_t index) {
+    list *lval = rnp_cfg_getlist(const_cast<rnp_cfg_t*>(cfg), key.c_str());
+    if (lval) {
+        if (index < list_length(*lval)) {
```
Comment (ni4) [inline src/rnp/rnpcfg.cpp]: Again, better return if index has wrong value, then nest further code.

File: src/rnpkeys/rnpkeys.cpp [hunk 13]
```diff
@@ -253,7 +263,15 @@ rnp_cmd(rnp_cfg_t *cfg, cli_rnp_t *rnp, optdefs_t cmd, const char *f)
         return import_keys(cfg, rnp, f);
     case CMD_GENERATE_KEY: {
         if (f == NULL) {
-            f = rnp_cfg_getstr(cfg, CFG_USERID);
+            list *ids = NULL;
+            if ((ids = rnp_cfg_getlist(cfg, CFG_USERID)) && list_length(*ids) > 0) {
+                if (list_length(*ids) == 1) {
+                    f = (fs = rnp_cfg_getlist_string(cfg, CFG_USERID, 0)).c_str();
+                }  else {
+                    fprintf(stderr, "only userid is supported for generated keys\n");
```
Comment (ni4) [inline src/rnpkeys/rnpkeys.cpp]: I guess it should be something like 'Only single userid' or 'Only one userid'.

File: src/tests/generatekey.cpp [hunk 14]
```diff
@@ -821,7 +832,7 @@ TEST_F(rnp_tests, generatekeyECDSA_explicitlySetBiggerThanNeededDigest_ShouldSuc
     assert_true(rnp_cfg_setstr(&ops, CFG_HASH, "SHA512"));
     assert_true(rnp_cfg_setint(&ops, CFG_S2K_ITER, 1));
 
-    assert_true(rnp_cfg_setstr(&ops, CFG_USERID, "expert_large_digest"));
+    assert_true(rnp_cfg_addstr(&ops, CFG_USERID, "expert_large_digest"));
```
Comment (ni4) [inline src/tests/generatekey.cpp]: We should also have negative test case - where two user ids are specified and key generation fails.

**Comment by joke325** [comment]
@ni4 Could you please look at the failure in Cirrus CI / build. I don't understand how my last commit causes the error in the cli_tests.py / Misc::test_encryption_s2k test. I cannot reproduce the failure on my machine.

**Comment by ni4** [comment]
@joke325 Looks like some problem on GnuPG side. I filed issue #984 to take a look later, and restarted test - let's see whether it helps.

File: src/rnpkeys/rnpkeys.cpp [hunk 15]
```diff
@@ -230,15 +230,25 @@ bool
...
     const char *key;
+    std::string fs;
 
     switch (cmd) {
     case CMD_LIST_KEYS:
         if (!f) {
-            f = rnp_cfg_getstr(cfg, CFG_USERID);
+            list *ids = NULL;
+            if ((ids = rnp_cfg_getlist(cfg, CFG_USERID)) && list_length(*ids) > 0) {
+                f = (fs = rnp_cfg_getlist_string(cfg, CFG_USERID, 0)).c_str();
```
Comment (ni4) [inline src/rnpkeys/rnpkeys.cpp]: I missed it during the previous review - if you don't use fs later on then it would be enough to write `f = rnp_cfg_getlist_string(cfg, CFG_USERID, 0).c_str()`.

File: src/tests/generatekey.cpp [hunk 16]
```diff
@@ -812,6 +823,22 @@ TEST_F(rnp_tests, generatekeyECDSA_explicitlySetSmallOutputDigest_DigestAlgAdjus
     rnp_cfg_free(&ops);
 }
 
+TEST_F(rnp_tests, generatekey_multipleUserIds_ShouldFail)
```
Comment (ni4) [inline src/tests/generatekey.cpp]: Please also add a line with test's declaration to rnp_tests.h.
While technically it is not needed it is sometimes handy to have all test names in one header. Or, if not - remove it completely in some separate PR.

File: src/rnpkeys/rnpkeys.cpp (hunk 15 above)
Comment (joke325) [reply src/rnpkeys/rnpkeys.cpp]: I believe the fs used to keep values of strings, pointers from c_str() won't work without the fs.

Comment (ni4) [reply src/rnpkeys/rnpkeys.cpp]: Oh, agreed. Missed this side, sorry.
