### PR TITLE
Correct key fields calculation and sigs validation.

### LINKED ISSUE #1020: Incorrect key flags check in transferable_subkey_bind()
## Description

As per RFC 4880 bis 8, if subkey is able to sign then primary key binding signature should be added as the subpacket to the subkey binding signature.
We doing this check as the following:
```
    realkf = (pgp_key_flags_t) binding->key_flags;
    if (!realkf) {
        realkf = pgp_pk_alg_capabilities(key->alg);
    }
```
Obviously, we should use `pgp_pk_alg_capabilities(subkey->alg)` here.

While it's easy to fix the code, the test which reproduces this case on level of function `pgp_generate_subkey` should be added.
Checks should be done for both set/unset `binding->key_flags` and with both sign-able/sign-unable subkey.

### LINKED ISSUE #1089: RNP and GPG report different key expiration times
## Description

For a key that was extended, RNP reports that the key has expired at an earlier time - not at the most recent expiration time.

## Steps to Reproduce

1. Import key 698e2885c1de74e32cd503ad295c746984af7f0c with rnpkeys
2. rnp --list 698e2885c1de74e32cd503ad295c746984af7f0c |grep EXPIRED

## Expected Behavior

GPG reports expiration date: 2020-03-17

## Actual Behavior

RNP reports expiration date 2018-04-12

### LINKED ISSUE #1092: test_ffi_signatures_dump test failure
## Description

I'm guessing a key expired

```
[ RUN      ] rnp_tests.test_ffi_signatures_dump
[signature_check_certification() /Users/runner/runners/2.165.2/work/rnp/rnp/src/librepgp/stream-sig.cpp:1203] key expired 532049 seconds ago
```

### PR DESCRIPTION
**Pull request by ni4**
This is a bit wide PR is part of the work on ability to update key expiration (as well as other fields).
Main feature here is moving from old incorrect way of key fields calculation (previously we just set key fields once new signature is added, without checking sigs validity and creation date).
Now it behave correctly by using data only from valid self-signatures, using the latest one as the source of key data (as key expiration, preferred algorithms and so on).

As a side effect of the changes different not so clearly related things were fixed here:
- issue #1092 (expired key)
- issue #1089 (wrong key expiration time)
- incorrect generation of subkey revocation signature
- issue #1020 (wrong subkey flags check)

Normally I would issue separate PRs for all these things, but now I'm a bit on rush with Thunderbird features implementation so allowed myself to put all these things into the single PR.

Fixes #1092, fixes #1089, fixes #1020.

### CODE REVIEW

File: src/librepgp/stream-key.cpp [hunk 1]
```diff
@@ -353,6 +353,54 @@ transferable_key_add_userid(pgp_transferable_key_t *key, const char *userid)
...
+                                  pgp_signature_t *       sig,
+                                  const pgp_key_pkt_t *   signer)
+{
+    if (!key || !uid || !sig || !signer) {
+        RNP_LOG("NULL parameter(s)");
+        return false;
+    }
+
+    rng_t rng = {};
+    if (!rng_init(&rng, RNG_SYSTEM)) {
```
Comment (dewyatt) [inline src/librepgp/stream-key.cpp:368]: The plan has been to drop `RNG_SYSTEM` at some point, so I'd rather see if we can pass the `rng_t` down through the various layers instead.

File: src/librepgp/stream-key.cpp [hunk 2]
```diff
@@ -353,6 +353,54 @@ transferable_key_add_userid(pgp_transferable_key_t *key, const char *userid)
...
+                           pgp_signature_t *    sig,
+                           const pgp_key_pkt_t *signer)
+{
+    if (!key || !sig || !signer) {
+        RNP_LOG("NULL parameter(s)");
+        return false;
+    }
+
+    rng_t rng = {};
+    if (!rng_init(&rng, RNG_SYSTEM)) {
```
Comment (dewyatt) [inline src/librepgp/stream-key.cpp:392]: Same here

File: src/lib/pgp-key.cpp [hunk 3]
```diff
@@ -961,6 +969,373 @@ pgp_key_get_subsig(const pgp_key_t *key, size_t idx)
...
+    /* validate self-signatures if not done yet */
+    if (key) {
+        pgp_subkey_validate_self_signatures(sub, key);
+    }
+    pgp_subsig_t *sig = pgp_key_latest_binding(sub, key);
+    /* subkey expiration */
+    sub->expiration = sig ? signature_get_key_expiration(&sig->sig) : 0;
+    /* subkey flags */
+    if (sig && signature_has_key_flags(&sig->sig)) {
+        sub->key_flags = sig->key_flags;
```
Comment (dewyatt) [inline src/lib/pgp-key.cpp:1252]: It seems like this would leave an incorrect value here in the case where a `PGP_SIG_SUBPKT_KEY_FLAGS` subpacket was previously present and has now been removed, wouldn't it?

File: src/lib/pgp-key.cpp [hunk 4]
```diff
@@ -961,6 +969,373 @@ pgp_key_get_subsig(const pgp_key_t *key, size_t idx)
...
+    }
+    if (signature_has_key_server_prefs(&subsig->sig)) {
+        uint8_t ks_pref = signature_get_key_server_prefs(&subsig->sig);
+        if (!pgp_user_prefs_set_ks_prefs(&subsig->prefs, &ks_pref, 1)) {
+            RNP_LOG("failed to alloc ks prefs");
+            goto error;
+        }
+    }
+    if (signature_has_key_server(&subsig->sig)) {
+        subsig->prefs.key_server = (uint8_t *) signature_get_key_server(&subsig->sig);
```
[the remark this answers is not in the document]
Comment (ni4) [reply src/lib/pgp-key.cpp:1012]: Thanks, fixed this.

File: src/lib/pgp-key.cpp (hunk 3 above)
Comment (ni4) [reply src/lib/pgp-key.cpp:1256]: Agree, thanks for spotting this. Fixed.

File: src/librepgp/stream-key.cpp (hunk 1 above)
Comment (ni4) [reply src/librepgp/stream-key.cpp:368]: @dewyatt What about moving this to the separate PR? Since it would require changing a lot of internal function declarations, as I think we don't want to make it global static variable.

Comment (dewyatt) [reply src/librepgp/stream-key.cpp:368]: @ni4 Sounds good to me

**Comment by ni4** [comment]
@ronaldtse @rrrooommmaaa Could you review this please, so we can move forward?

**Comment by ni4** [comment]
@ronaldtse Thanks! So merging this, considering that Windows fails because of GHA.

**Comment by ronaldtse** [comment]
Thanks @ni4 !
