### PR TITLE
CLI: prevent endless loop in rnpkeys expert mode.

### LINKED ISSUE #969: rnpkeys: possible endless loop with endless output.
## Description

Using rnpkeys expert key generation mode with redirected input/output, and incorrect/empty stdin, may become endless producing endless output (just got 30Gb+ log file while running incorrectly configured tests).

Correct behavior would be to ask for input for few times and terminate, and to check whether stdin is opened at all.

### PR DESCRIPTION
**Pull request by antonsviridenko**
Fixes #969

### CODE REVIEW

File: src/rnpkeys/tui.cpp [hunk 1]
```diff
@@ -77,6 +79,17 @@ rnp_secure_get_long_from_fd(FILE *fp, long &result, bool allow_empty = true)
     return true;
 }
 
+static bool
+check_attempts(int *attempts)
```
Comment (ni4) [inline src/rnpkeys/tui.cpp:83]: It would be more clear to use `int &attempts` here.

**Comment by ni4** [comment]
@antonsviridenko nix fix landed main, so feel free to rebase.

**Review by ronaldtse — APPROVED** [review]

**Comment by ronaldtse** [comment]
I've just made the rebase, let's see what happens.
